const TEAMS=['Brandon','Phillip','Andy','Hunter','Dave','Cody','Chris','Brian','Scott','Sean'];
const KEY='draftiq_v6';
const P=window.DRAFTIQ_PLAYERS||[];
const META=window.DRAFTIQ_DATA_META||{};
const defaults={teams:[['Scott','Josh Allen','Jahmyr Gibbs','Justin Jefferson','Ashton Jeanty'],['Brandon','Jaxson Dart','Bijan Robinson','Amon-Ra St. Brown','Jaxon Smith-Njigba'],['Phillip','Joe Burrow',"De'Von Achane","Ja'Marr Chase",'Puka Nacua'],['Andy','Jalen Hurts','Saquon Barkley','Jonathan Taylor','Nico Collins'],['Hunter','','','',''],['Dave','','','',''],['Cody','','','',''],['Chris','','','',''],['Brian','','','',''],['Sean','','','','']],draft:[],targets:[],pick:1,owners:{1:'Scott',29:'Traded Away'}};
let s=JSON.parse(localStorage.getItem(KEY)||'null')||defaults;
s.teams=s.teams||defaults.teams;s.draft=s.draft||[];s.targets=s.targets||[];s.owners=s.owners||defaults.owners;
function save(){localStorage.setItem(KEY,JSON.stringify(s));}
save();
const $=id=>document.getElementById(id);const E=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const U=x=>encodeURIComponent(String(x??''));
const norm=n=>String(n||'').toLowerCase().replace(/[^a-z0-9]/g,'');
const aliases={'jamescook':'jamescookiii','kylepitts':'kylepittssr','chrisgodwin':'chrisgodwinjr','aaronjones':'aaronjonessr','deebosamuel':'deebosamuelsr'};
function keyName(n){let k=norm(n);return aliases[k]||k;}
function player(n){let k=keyName(n);return P.find(p=>keyName(p[0])===k);}
function baseOwner(p){return TEAMS[(p-1)%10];}
function owner(p){return s.owners[p]||baseOwner(p);}
function round(p){return Math.ceil(p/10);}
function keeperNames(){return new Set(s.teams.flatMap(t=>t.slice(1).filter(Boolean).map(keyName)));}
function taken(){let z=new Set(s.draft.map(x=>keyName(x.name)));keeperNames().forEach(x=>z.add(x));return z;}
function available(){let z=taken();return P.filter(p=>!z.has(keyName(p[0])));}
function myRoster(){let a=s.teams[0].slice(1).filter(Boolean).map(n=>({name:n,pos:player(n)?.[1]||'',keeper:true}));s.draft.filter(d=>d.team==='Scott').forEach(d=>a.push({name:d.name,pos:d.pos,keeper:false}));return a;}
function posNeed(pos){let n=myRoster().filter(x=>x.pos===pos).length;if(pos==='QB')return n?8:75;if(pos==='RB')return Math.max(18,90-n*23);if(pos==='WR')return Math.max(20,95-n*20);if(pos==='TE')return n?25:58;return 20;}
function targetLevel(n){return s.targets.find(t=>keyName(t.name)===keyName(n))?.level||0;}
function nextMine(){for(let p=s.pick+1;p<=120;p++)if(owner(p)==='Scott')return p;return null;}
function survival(p){let nx=nextMine();if(!nx)return 100;let ahead=available().filter(x=>x[2]<p[2]).length;let gap=nx-s.pick;return Math.max(4,Math.min(96,100-ahead*2.2-gap*2.4));}
function draftScore(p){let a=available(),max=Math.max(...a.map(x=>x[3]),1);return Math.min(100,(p[3]/max)*63+posNeed(p[1])*.22+(100-survival(p))*.08+targetLevel(p[0])*7);}
function rec(){return available().map(p=>({p,score:draftScore(p),surv:survival(p)})).sort((a,b)=>b.score-a.score);}
const pages=[['draft','Draft'],['board','Board'],['players','Available'],['targets','Targets'],['roster','My Roster'],['league','Keepers']];
function nav(v){$('nav').innerHTML=pages.map(x=>`<button class="${v===x[0]?'on':''}" onclick="view('${x[0]}')">${x[1]}</button>`).join('');}
function view(v){nav(v);$('status').textContent=`• Pick ${s.pick}/120 • ${owner(s.pick)}`;$('app').innerHTML=v==='draft'?draftView():v==='board'?boardView():v==='players'?playersView():v==='targets'?targetsView():v==='roster'?rosterView():leagueView();if(v==='players')filterPlayers();}
function draftView(){let r=rec(),b=r[0];return `<div class="grid"><section><div class="card hero"><div class="m">CURRENT PICK ${s.pick}/120 • ${E(owner(s.pick))} • ROUND ${round(s.pick)}</div>${b?`<h2>${E(b.p[0])}</h2><span class="pill">${b.p[1]} • 2026 baseline ${b.p[3].toFixed(1)} pts</span><div class="big">${b.score.toFixed(0)}</div><div class="m">DRAFTIQ SCORE</div><p>${b.surv<35?'⚠️ Low chance to survive until your next pick.':posNeed(b.p[1])>70?'Strong roster need plus projected value.':'Best blend of projection, roster fit and pick urgency.'}</p><button class="go" onclick="draftPlayer(decodeURIComponent('${U(b.p[0])}'))">DRAFT PLAYER</button>`:'<div class="notice">No players remain.</div>'}</div><div class="card"><h3>🔥 Suggested Players</h3>${r.slice(0,10).map(x=>`<div class="row"><span><b>${E(x.p[0])}</b><br><span class="m mini">${x.p[1]} • ${x.p[3].toFixed(1)} pts • ${x.surv.toFixed(0)}% next</span></span><b>${x.score.toFixed(0)}</b></div>`).join('')}</div></section><aside><div class="card"><h3>🔮 Around Next Pick</h3>${r.slice().sort((a,b)=>b.surv-a.surv).slice(0,8).map(x=>`<div class="row"><span>${E(x.p[0])}<br><small class="m">${x.p[1]}</small></span><b>${x.surv.toFixed(0)}%</b></div>`).join('')}</div><div class="card"><h3>🎯 Targets</h3>${s.targets.length?s.targets.map(t=>`<div class="row"><span>${E(t.name)}<br><small>${['','Watch','Target','Must Have'][t.level]}</small></span></div>`).join(''):'<span class="m">None yet.</span>'}</div></aside></div>`;}
function draftPlayer(n){let p=player(n);if(!p||round(s.pick)>12)return;s.draft=s.draft.filter(d=>d.pick!==s.pick);s.draft.push({pick:s.pick,team:owner(s.pick),name:p[0],pos:p[1]});s.pick=Math.min(120,s.pick+1);save();view('draft');}
function keeperAtPick(p){if(round(p)<13)return null;let team=owner(p),t=s.teams.find(x=>x[0]===team);if(!t)return null;return t[round(p)-12]||null;}
function boardView(){let rows='';for(let r=1;r<=16;r++){rows+=`<tr class="roundhead"><td colspan="4">ROUND ${r}${r>=13?' — KEEPER ROUND':''}</td></tr>`;for(let j=1;j<=10;j++){let p=(r-1)*10+j,d=s.draft.find(x=>x.pick===p),k=keeperAtPick(p),o=owner(p);rows+=`<tr class="${r>=13?'keeper ':''}${o==='Scott'?'mine':''}"><td>${r}.${String(j).padStart(2,'0')}</td><td>${E(o)}</td><td>${k?E(k)+' <span class="pill">KEEPER</span>':d?E(d.name):'—'}</td><td>${r<=12?`<button onclick="setPick(${p})">Set</button>`:''}</td></tr>`;}}return `<div class="card"><h2>📋 Draft Board</h2><div class="notice">Scott owns 1.01 plus the 9th slot each round; 3.09 is marked traded away. Use the trade tool below when pick ownership changes.</div><div class="trade"><select id="tradeA">${pickOptions()}</select><select id="tradeB">${pickOptions()}</select><button onclick="swapPicks()">Swap Pick Owners</button></div><table><tr><th>Pick</th><th>Owner</th><th>Player</th><th></th></tr>${rows}</table></div>`;}
function pickOptions(){return Array.from({length:120},(_,i)=>{let p=i+1;return `<option value="${p}">${round(p)}.${String(((p-1)%10)+1).padStart(2,'0')} — ${E(owner(p))}</option>`}).join('');}
function swapPicks(){let a=+$('tradeA').value,b=+$('tradeB').value,oa=owner(a),ob=owner(b);s.owners[a]=ob;s.owners[b]=oa;save();view('board');}
function setPick(p){s.pick=p;save();view('draft');}
function playersView(){return `<div class="card"><h2>Available Players <span class="m">(${available().length})</span></h2><div class="notice">Expanded player data is stored separately from the app. Keeper players are automatically excluded.</div><div class="filters"><input id="q" placeholder="Search player..." oninput="filterPlayers()"><select id="pos" onchange="filterPlayers()"><option value="">All</option><option>QB</option><option>RB</option><option>WR</option><option>TE</option></select><select id="sort" onchange="filterPlayers()"><option value="score">DraftIQ Score</option><option value="proj">Projected Points</option><option value="rank">Overall Rank</option><option value="target">Target Priority</option><option value="surv">Chance to Reach Next Pick</option></select></div><div id="plist"></div></div>`;}
function filterPlayers(){if(!$('plist'))return;let q=($('q').value||'').toLowerCase(),po=$('pos').value,sort=$('sort').value,a=rec().filter(x=>(!q||x.p[0].toLowerCase().includes(q))&&(!po||x.p[1]===po));a.sort((x,y)=>sort==='proj'?y.p[3]-x.p[3]:sort==='rank'?x.p[2]-y.p[2]:sort==='target'?targetLevel(y.p[0])-targetLevel(x.p[0])||y.score-x.score:sort==='surv'?y.surv-x.surv:y.score-x.score);$('plist').innerHTML=a.map(x=>`<div class="row ${targetLevel(x.p[0])?'targeted':''}"><span><b>${E(x.p[0])}</b> <span class="pill">${x.p[1]}</span><br><span class="m mini">Rank ${x.p[2]} • ${x.p[3].toFixed(1)} pts • DraftIQ ${x.score.toFixed(0)} • ${x.surv.toFixed(0)}% next</span></span>${targetLevel(x.p[0])?`<button onclick="removeTarget(decodeURIComponent('${U(x.p[0])}'))">✓ Targeted</button>`:`<button onclick="addTarget(decodeURIComponent('${U(x.p[0])}'),2)">＋ Target</button>`}</div>`).join('')||'<div class="notice">No matching players.</div>';}
function targetsView(){return `<div class="card"><h2>🎯 My Targets</h2>${s.targets.length?s.targets.map(t=>`<div class="row"><span><b>${E(t.name)}</b><br><small>${['','Watch','Target','Must Have'][t.level]}</small></span><span><button onclick="cycleTarget(decodeURIComponent('${U(t.name)}'))">Change</button> <button class="red" onclick="removeTarget(decodeURIComponent('${U(t.name)}'))">Remove</button></span></div>`).join(''):'<span class="m">No targets yet. Add them from Available.</span>'}</div>`;}
function addTarget(n,l){s.targets=s.targets.filter(t=>keyName(t.name)!==keyName(n));s.targets.push({name:n,level:l||2});save();view('targets');}
function removeTarget(n){s.targets=s.targets.filter(t=>keyName(t.name)!==keyName(n));save();view('targets');}
function cycleTarget(n){let t=s.targets.find(x=>keyName(x.name)===keyName(n));if(t)t.level=t.level>=3?1:t.level+1;save();view('targets');}
function rosterView(){return `<div class="card"><h2>👤 My Roster</h2>${myRoster().map(x=>`<div class="row"><span><b>${E(x.name)}</b><br><small class="m">${x.pos||'Unknown position'}</small></span>${x.keeper?'<span class="pill">KEEPER</span>':''}</div>`).join('')}</div>`;}
function leagueView(){return `<div class="card"><h2>👥 Teams & Keepers</h2><div class="notice">Your saved keeper data is preserved in the same browser storage. Changes immediately update Available and Suggested.</div><table><tr><th>Team</th><th>Keeper 1</th><th>Keeper 2</th><th>Keeper 3</th><th>Keeper 4</th></tr>${s.teams.map((t,i)=>`<tr><td><b>${E(t[0])}</b></td>${[1,2,3,4].map(j=>`<td><input value="${E(t[j]||'')}" onchange="keeper(${i},${j},this.value)"></td>`).join('')}</tr>`).join('')}</table><div class="notice" style="margin-top:12px">Player dataset: ${E(META.source||'2026 projections')} • Updated ${E(META.updated||'')}</div></div>`;}
function keeper(i,j,v){s.teams[i][j]=v.trim();save();view('league');}
view('draft');