(function(){
const OWNER_TEAMS={Sean:'JIMBO SLICE',Chris:"chris's First-Rate Team",Brian:"Ethan’s Dogshit Team",Hunter:'JUDKINS OUT ON BOND',Andy:'Insert in my Tight end',Cody:"Najee see me najee don't",Dave:'STOP.. Caleb-a-rate and Listen',Brandon:'Kickers are people too',Scott:'Rice Rice Baby',Phillip:"Philip's Pleasant Team"};
const TEAM_NAMES={ARI:'Arizona Cardinals',ATL:'Atlanta Falcons',BAL:'Baltimore Ravens',BUF:'Buffalo Bills',CAR:'Carolina Panthers',CHI:'Chicago Bears',CIN:'Cincinnati Bengals',CLE:'Cleveland Browns',DAL:'Dallas Cowboys',DEN:'Denver Broncos',DET:'Detroit Lions',GB:'Green Bay Packers',HOU:'Houston Texans',IND:'Indianapolis Colts',JAX:'Jacksonville Jaguars',KC:'Kansas City Chiefs',LAC:'Los Angeles Chargers',LAR:'Los Angeles Rams',LV:'Las Vegas Raiders',MIA:'Miami Dolphins',MIN:'Minnesota Vikings',NE:'New England Patriots',NO:'New Orleans Saints',NYG:'New York Giants',NYJ:'New York Jets',PHI:'Philadelphia Eagles',PIT:'Pittsburgh Steelers',SEA:'Seattle Seahawks',SF:'San Francisco 49ers',TB:'Tampa Bay Buccaneers',TEN:'Tennessee Titans',WAS:'Washington Commanders'};
const BYE={KC:5,CAR:5,CIN:6,DET:6,MIA:6,MIN:6,BUF:7,JAX:7,LAC:7,WAS:7,NYG:8,HOU:8,NO:8,SF:8,PIT:9,TEN:9,CHI:10,DEN:10,PHI:10,TB:10,SEA:11,LAR:11,ATL:11,NE:11,CLE:11,GB:11,BAL:13,NYJ:13,IND:13,LV:13,DAL:14,ARI:14};
let sleeper={};let metadataReady=false;let currentPage='command';
function initials(n){return String(n||'?').split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase()}
function meta(name){const m=sleeper[keyName(name)]||{};const team=m.team||'';return {team,teamName:TEAM_NAMES[team]||team||'Team TBD',bye:BYE[team]||'—',photo:m.player_id?`https://sleepercdn.com/content/nfl/players/${m.player_id}.jpg`:''}}
function avatar(name,cls=''){const m=meta(name);return m.photo?`<img class="${cls}" src="${m.photo}" alt="" loading="lazy" decoding="async" onerror="this.outerHTML='<span class=&quot;avatar-fallback ${cls}&quot;>${initials(name)}</span>'">`:`<span class="avatar-fallback ${cls}">${initials(name)}</span>`}
function nflLine(name,pos){const m=meta(name);return `<span class="pos-${pos}">${pos||'—'}</span> • ${m.team||'TBD'} • Bye ${m.bye}`}
window.DraftIQAvatar=avatar;window.DraftIQNFLLine=nflLine;window.DraftIQMeta=meta;
function fantasyTeam(ownerName){return OWNER_TEAMS[ownerName]||ownerName}
function rosterLimit(){return 16}
function statIcon(type){return type==='pick'?'⚑':type==='next'?'◷':type==='until'?'▷':'♙'}
const baseView=view;
view=function(v){currentPage=v;document.body.classList.toggle('command-active',v==='command');baseView(v);if(v==='players')filterPlayers();};
commandView=function(){
 const r=rec(),best=r[0],nx=nextMineIncludingCurrent(),future=nextMine(),between=nx===s.pick?0:(future?Math.max(0,future-s.pick-1):0),cr=round(s.pick),start=(cr-1)*10+1;
 const likely=r.slice().sort((a,b)=>b.surv-a.surv||b.score-a.score).slice(0,5);
 const targets=s.targets.filter(t=>{const p=player(t.name);return p&&!taken().has(keyName(t.name))}).slice(0,5);
 const roster=myRoster().slice(0,7);
 const board=Array.from({length:10},(_,i)=>{const p=start+i,d=s.draft.find(x=>x.pick===p),o=owner(p);return `<tr class="${p===s.pick?'active-pick ':''}${o==='Scott'?'mine':''}"><td>${fmtPick(p)}</td><td><b>${E(fantasyTeam(o))}</b><br><span class="m">${E(o)}</span></td><td>${d?E(d.name):p===s.pick?'<span class="clock">ON THE CLOCK</span>':'—'}</td></tr>`}).join('');
 const topAction=s.draft.length?`<button onclick="undoLastPick()">↶ Undo Last Pick</button>`:`<button disabled>↶ Undo Last Pick</button>`;
 const teamName=OWNER_TEAMS.Scott;
 return `<div class="cc-shell"><div class="cc-toolbar">${topAction}<button>10 Team League⌄</button></div><div class="cc-stats">
 <div class="cc-stat"><div class="cc-stat-icon">${statIcon('pick')}</div><div class="cc-stat-copy"><div class="cc-stat-label">Current Pick</div><div class="cc-stat-value">${fmtPick(s.pick)}</div><div class="cc-stat-sub"><strong>${E(owner(s.pick))}${owner(s.pick)==='Scott'?' (You)':''}</strong><br>${E(fantasyTeam(owner(s.pick)))}</div></div></div>
 <div class="cc-stat"><div class="cc-stat-icon">${statIcon('next')}</div><div class="cc-stat-copy"><div class="cc-stat-label">Next Pick</div><div class="cc-stat-value">${nx?fmtPick(nx):'—'}</div><div class="cc-stat-sub">${nx?`Scott<br>${E(teamName)}`:'Draft complete'}</div></div></div>
 <div class="cc-stat"><div class="cc-stat-icon">${statIcon('until')}</div><div class="cc-stat-copy"><div class="cc-stat-label">Picks Until Next</div><div class="cc-stat-value">${between}</div><div class="cc-stat-sub ${nx===s.pick?'green':''}">${nx===s.pick?'On the Clock':future?`Next at ${fmtPick(future)}`:'—'}</div></div></div>
 <div class="cc-stat"><div class="cc-stat-icon">${statIcon('roster')}</div><div class="cc-stat-copy"><div class="cc-stat-label">Roster</div><div class="cc-stat-value">${myRoster().length} / ${rosterLimit()}</div><div class="cc-stat-sub">${myRoster().length} players<br>${Math.max(0,rosterLimit()-myRoster().length)} spots left</div></div></div></div>
 <div class="cc-grid"><section class="cockpit-panel"><div class="panel-title"><h3>DraftIQ Recommendation</h3><button onclick="view('draft')">Open Assistant →</button></div>${best?`<div class="recommend-card">${avatar(best.p[0],'recommend-photo')}<div class="recommend-info"><h2>${E(best.p[0])}</h2><div class="meta">${nflLine(best.p[0],best.p[1])}</div></div><div class="recommend-score"><strong>${best.score.toFixed(1)}</strong><small>DraftIQ Score</small></div></div><div class="recommend-metrics"><div><span>Rank</span><b>${best.p[2]}</b></div><div><span>Proj Pts</span><b>${best.p[3].toFixed(1)}</b></div><div><span>Bye</span><b>${meta(best.p[0]).bye}</b></div><div><span>Chance to Next</span><b class="warn">${best.surv}%</b></div></div><button class="go recommend-action" onclick="draftPlayer(decodeURIComponent('${U(best.p[0])}'))">Draft This Player</button>`:'<div class="m">No players remain.</div>'}</section>
 <section class="cockpit-panel"><div class="panel-title"><h3>Best Available (Top 5)</h3><button onclick="view('players')">View All →</button></div><div class="player-list">${r.slice(0,5).map((x,i)=>`<div class="player-line"><span>${i+1}</span>${avatar(x.p[0])}<div class="name"><b>${E(x.p[0])}</b><small>${nflLine(x.p[0],x.p[1])}</small></div><div class="value">${x.score.toFixed(1)}</div></div>`).join('')}</div></section>
 <section class="cockpit-panel"><div class="panel-title"><h3>Likely At Your Next Pick (Top 5)</h3><button onclick="view('players')">Full List →</button></div><div class="player-list">${likely.map((x,i)=>`<div class="player-line"><span>${i+1}</span>${avatar(x.p[0])}<div class="name"><b>${E(x.p[0])}</b><small>${nflLine(x.p[0],x.p[1])}</small></div><div class="value">${x.surv}%</div></div>`).join('')}</div></section>
 <section class="cockpit-panel"><div class="panel-title"><h3>My Team</h3><button onclick="view('roster')">View Full Team →</button></div><table class="roster-table"><tr><th>Pos</th><th>Player</th><th>Bye</th><th>Proj</th></tr>${roster.map(x=>{const p=player(x.name),m=meta(x.name);return `<tr><td class="pos-${x.pos}">${x.pos||'—'}</td><td><div class="player-cell">${avatar(x.name)}<span><b>${E(x.name)}</b><br><small class="m">${m.team||'TBD'}</small></span></div></td><td>${m.bye}</td><td>${p?p[3].toFixed(1):'—'}</td></tr>`}).join('')}</table></section>
 <section class="cockpit-panel"><div class="panel-title"><h3>My Targets (Top 5)</h3><button onclick="view('targets')">View All Targets →</button></div><div class="player-list">${targets.length?targets.map((t,i)=>{const p=player(t.name),m=meta(t.name);return `<div class="player-line"><span>${i+1}</span>${avatar(t.name)}<div class="name"><b>${E(t.name)}</b><small>${nflLine(t.name,p?.[1]||'')}</small></div><button class="target-remove" onclick="removeTargetCommand(decodeURIComponent('${U(t.name)}'))">×</button></div>`}).join(''):'<div class="m">No available targets.</div>'}</div></section>
 <section class="cockpit-panel"><div class="panel-title"><h3>Draft Board (Round ${cr})</h3><button onclick="view('board')">View Full Board →</button></div><table class="board-compact"><tr><th>Pick</th><th>Team</th><th>Player</th></tr>${board}</table></section></div>
 <div class="cc-footer"><span>Red Zone Fantasy Draft</span><span>10 Teams &nbsp; • &nbsp; 16 Rounds &nbsp; • &nbsp; PPR / 6-pt Pass TD</span><span>Auto-save: On <span class="ok">✓</span></span></div></div>`;
};
const baseFilter=filterPlayers;
filterPlayers=function(){if(!$('plist'))return;let q=($('q').value||'').toLowerCase(),po=$('pos').value,sort=$('sort').value,a=rec().filter(x=>(!q||x.p[0].toLowerCase().includes(q))&&(!po||x.p[1]===po));a.sort((x,y)=>sort==='proj'?y.p[3]-x.p[3]:sort==='rank'?x.p[2]-y.p[2]:sort==='target'?targetLevel(y.p[0])-targetLevel(x.p[0])||y.score-x.score:sort==='surv'?y.surv-x.surv:y.score-x.score);$('plist').innerHTML=a.map(x=>{const m=meta(x.p[0]);return `<div class="row ${targetLevel(x.p[0])?'targeted':''}"><span style="display:flex;align-items:center;gap:9px">${avatar(x.p[0])}<span><b>${E(x.p[0])}</b> <span class="pill pos-${x.p[1]}">${x.p[1]}</span><br><span class="m mini">${m.teamName} • Bye ${m.bye} • Rank ${x.p[2]} • ${x.p[3].toFixed(1)} pts • DraftIQ ${x.score.toFixed(0)} • ${x.surv.toFixed(0)}% next</span></span></span>${targetLevel(x.p[0])?`<button onclick="removeTargetHere(decodeURIComponent('${U(x.p[0])}'))">✓ Targeted</button>`:`<button onclick="addTargetHere(decodeURIComponent('${U(x.p[0])}'),2)">＋ Target</button>`}</div>`}).join('')||'<div class="m">No matching players.</div>';};
async function loadMetadata(){try{const res=await fetch('https://api.sleeper.app/v1/players/nfl',{cache:'force-cache'});if(!res.ok)throw new Error('metadata');const data=await res.json();for(const id in data){const p=data[id];if(!p||!p.full_name)continue;sleeper[keyName(p.full_name)]={player_id:p.player_id||id,team:p.team||''};}metadataReady=true;if(currentPage==='command')view('command');else if(currentPage==='players')view('players');}catch(e){metadataReady=false;}}
loadMetadata();view('command');
})();