(function(){
const FANTASY_NAMES={Sean:'JIMBO SLICE',Chris:"chris's First-Rate Team",Brian:"Ethan’s Dogshit Team",Hunter:'JUDKINS OUT ON BOND',Andy:'Insert in my Tight end',Cody:"Najee see me najee don't",Dave:'STOP.. Caleb-a-rate and Listen',Brandon:'Kickers are people too',Scott:'Rice Rice Baby',Phillip:"Philip's Pleasant Team"};
const TEAM_NAMES={ARI:'Arizona Cardinals',ATL:'Atlanta Falcons',BAL:'Baltimore Ravens',BUF:'Buffalo Bills',CAR:'Carolina Panthers',CHI:'Chicago Bears',CIN:'Cincinnati Bengals',CLE:'Cleveland Browns',DAL:'Dallas Cowboys',DEN:'Denver Broncos',DET:'Detroit Lions',GB:'Green Bay Packers',HOU:'Houston Texans',IND:'Indianapolis Colts',JAX:'Jacksonville Jaguars',KC:'Kansas City Chiefs',LAC:'Los Angeles Chargers',LAR:'Los Angeles Rams',LV:'Las Vegas Raiders',MIA:'Miami Dolphins',MIN:'Minnesota Vikings',NE:'New England Patriots',NO:'New Orleans Saints',NYG:'New York Giants',NYJ:'New York Jets',PHI:'Philadelphia Eagles',PIT:'Pittsburgh Steelers',SEA:'Seattle Seahawks',SF:'San Francisco 49ers',TB:'Tampa Bay Buccaneers',TEN:'Tennessee Titans',WAS:'Washington Commanders'};
const BYE={KC:5,CAR:5,CIN:6,DET:6,MIA:6,MIN:6,BUF:7,JAX:7,LAC:7,WAS:7,NYG:8,HOU:8,NO:8,SF:8,PIT:9,TEN:9,CHI:10,DEN:10,PHI:10,TB:10,SEA:11,LAR:11,ATL:11,NE:11,CLE:11,GB:11,BAL:13,NYJ:13,IND:13,LV:13,DAL:14,ARI:14};
let metaCache={};
function fantasyName(owner){return FANTASY_NAMES[owner]||owner;}
function posCounts(roster){const out={QB:0,RB:0,WR:0,TE:0};roster.forEach(x=>{if(out[x.pos]!==undefined)out[x.pos]++});return out;}
function ownerPickCount(ownerName){let n=0;for(let p=1;p<=120;p++)if(owner(p)===ownerName)n++;return n;}
function initials(n){return String(n||'?').split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase();}
function meta(name){return metaCache[keyName(name)]||{team:'',player_id:''};}
function avatar(name){const m=meta(name);return m.player_id?`<img class="lr-avatar" src="https://sleepercdn.com/content/nfl/players/thumb/${m.player_id}.jpg" alt="" onerror="this.outerHTML='<span class=&quot;lr-avatar lr-fallback&quot;>${initials(name)}</span>'">`:`<span class="lr-avatar lr-fallback">${initials(name)}</span>`;}
function teamLine(name,pos){const m=meta(name),t=m.team||'TBD';return `${pos||'—'} • ${TEAM_NAMES[t]||t} • Bye ${BYE[t]||'—'}`;}
function playerRow(x){const p=player(x.name);return `<div class="lr-player"><div class="lr-pos pos-${x.pos}">${x.pos||'—'}</div>${avatar(x.name)}<div class="lr-player-main"><b>${E(x.name)}</b><small>${E(teamLine(x.name,x.pos))}</small></div><div class="lr-player-right">${x.keeper?'<span class="lr-badge keeper-badge">KEEPER</span>':`<span class="lr-badge draft-badge">${x.pick?fmtPick(x.pick):'DRAFTED'}</span>`}${p?`<small>${p[3].toFixed(1)} pts</small>`:''}</div></div>`;}
teamsView=function(){
 const totalDrafted=s.draft.length,totalRostered=TEAMS.reduce((sum,t)=>sum+teamRoster(t).length,0),keeperTotal=TEAMS.reduce((sum,t)=>sum+keeperList(t).length,0);
 const cards=TEAMS.map((ownerName,idx)=>{const roster=teamRoster(ownerName),counts=posCounts(roster),drafted=roster.filter(x=>!x.keeper).length,keepers=roster.filter(x=>x.keeper).length;return `<section class="lr-team-card ${ownerName==='Scott'?'lr-my-team':''}"><div class="lr-team-head"><div><div class="lr-seed">TEAM ${String(idx+1).padStart(2,'0')}</div><h3>${E(fantasyName(ownerName))}</h3><small>Manager: ${E(ownerName)}${ownerName==='Scott'?' • YOUR TEAM':''}</small></div><div class="lr-record"><strong>${roster.length}</strong><span>/ 16</span></div></div><div class="lr-team-meta"><span>${keepers} Keepers</span><span>${drafted} Drafted</span><span>${ownerPickCount(ownerName)} Picks Owned</span></div><div class="lr-pos-strip"><span class="pos-QB">QB <b>${counts.QB}</b></span><span class="pos-RB">RB <b>${counts.RB}</b></span><span class="pos-WR">WR <b>${counts.WR}</b></span><span class="pos-TE">TE <b>${counts.TE}</b></span></div><div class="lr-roster">${roster.length?roster.map(playerRow).join(''):'<div class="lr-empty">No keepers or draft selections yet.</div>'}</div></section>`}).join('');
 return `<div class="lr-page"><div class="lr-hero"><div><div class="lr-kicker">RED ZONE LEAGUE OFFICE</div><h2>Official League Rosters</h2><p>Live roster ledger for all 10 franchises. Keeper and draft activity updates automatically across devices.</p></div><div class="lr-live"><span></span> LIVE</div></div><div class="lr-summary"><div><span>Franchises</span><strong>10</strong></div><div><span>Players Rostered</span><strong>${totalRostered}</strong></div><div><span>Keepers Locked</span><strong>${keeperTotal}</strong></div><div><span>Draft Picks Made</span><strong>${totalDrafted}</strong></div></div><div class="lr-grid">${cards}</div></div>`;
};
async function loadLRMeta(){try{const r=await fetch('https://api.sleeper.app/v1/players/nfl',{cache:'force-cache'});if(!r.ok)return;const data=await r.json();for(const id in data){const x=data[id];if(x?.full_name)metaCache[keyName(x.full_name)]={team:x.team||'',player_id:x.player_id||id};}if(document.querySelector('.lr-page'))view('teams');}catch(e){}}
loadLRMeta();
})();