// FantasyPros news integration via Supabase Edge Function.
(function(){
const ENDPOINT='https://uinhyjqsqrgfczqrmcya.supabase.co/functions/v1/fantasypros-news';
let lastPlayer='';
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function strip(v){const d=document.createElement('div');d.innerHTML=String(v??'');return (d.textContent||d.innerText||'').replace(/view fantasy impact\s*»?/ig,'').trim();}
function age(v){if(!v)return '';let s=String(v).trim();if(/^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}$/.test(s))s=s.replace(' ','T')+'Z';const d=new Date(s);if(Number.isNaN(d.getTime()))return '';const m=Math.max(0,Math.floor((Date.now()-d.getTime())/60000));if(m<60)return `${m}m ago`;const h=Math.floor(m/60);if(h<24)return `${h}h ago`;return `${Math.floor(h/24)}d ago`;}
function items(data){const candidates=[data?.items,data?.news,data?.results,data?.data?.items,data?.data,data?.players?.news];for(const x of candidates)if(Array.isArray(x))return x;return Array.isArray(data)?data:[];}
function normalize(n){const cats=Array.isArray(n?.categories)?n.categories.join(' • '):'';return {title:n?.title||n?.headline||n?.news_headline||n?.player_name||'Player Update',body:strip(n?.desc||n?.description||n?.analysis||n?.news||n?.summary||n?.body||n?.content||''),impact:strip(n?.impact||n?.fantasy_impact||''),date:n?.created||n?.updated||n?.published_at||n?.updated_at||n?.created_at||n?.date||n?.timestamp||'',type:cats||n?.type||n?.category||n?.news_type||'',link:n?.link||n?.url||''};}
function panel(){return document.querySelector('.cc-area-rec')||Array.from(document.querySelectorAll('.cockpit-panel')).find(p=>p.querySelector('.panel-title h3')?.textContent.includes('DraftIQ Recommendation'));}
function recommendedName(p){return p?.querySelector('.recommend-info h2')?.textContent?.trim()||'';}
function mount(p){let box=p.querySelector('.fp-news');if(!box){box=document.createElement('div');box.className='fp-news';const action=p.querySelector('.recommend-action');if(action)action.before(box);else p.appendChild(box);}return box;}
function renderLoading(box){box.innerHTML='<div class="fp-news-head"><b>LATEST NEWS</b><span>FantasyPros</span></div><div class="fp-news-loading">Checking for recent player news…</div>';}
function diagnostic(data){const d=data?.debug||{};const p=d.player_lookup||{};return `DEBUG • lookup ${p.status??'—'} • matches ${p.match_count??'—'} • FPID ${d.resolved_fpid??p.resolved_fpid??'NONE'} • news ${d.news_status??'—'} • count ${d.news_count??d.item_count??data?.count??'—'}`;}
function render(box,data){const list=items(data).map(normalize).filter(x=>x.title||x.body||x.impact);if(!list.length){box.innerHTML=`<div class="fp-news-head"><b>LATEST NEWS</b><span>FantasyPros</span></div><div class="fp-news-empty">No recent FantasyPros news found for this player.</div><div style="margin-top:5px;font:700 8px/1.25 monospace;color:#b71920;word-break:break-word">${esc(diagnostic(data))}</div>`;return;}const n=list[0];const source=n.link?`<a class="fp-news-source" href="${esc(n.link)}" target="_blank" rel="noopener">FantasyPros ↗</a>`:'FantasyPros';box.innerHTML=`<div class="fp-news-head"><b>LATEST NEWS</b><span>${esc(n.type||'Player News')}${n.date?` • ${esc(age(n.date))}`:''}</span></div><div class="fp-news-title">${esc(n.title)}</div>${n.body?`<div class="fp-news-body">${esc(n.body)}</div>`:''}${n.impact?`<div class="fp-news-impact"><b>FANTASY IMPACT</b> ${esc(n.impact)}</div>`:''}<div class="fp-news-credit">${source}</div>`;}
function renderError(box,e){box.innerHTML=`<div class="fp-news-head"><b>LATEST NEWS</b><span>FantasyPros</span></div><div class="fp-news-empty">Player news temporarily unavailable.</div><div style="margin-top:5px;font:700 8px/1.25 monospace;color:#b71920">DEBUG • ${esc(e?.message||e||'request failed')}</div>`;}
async function load(name,box){renderLoading(box);try{const r=await fetch(`${ENDPOINT}?player=${encodeURIComponent(name)}&limit=3&_=${Date.now()}`,{cache:'no-store'});const data=await r.json();if(!r.ok)throw new Error(data?.error||`HTTP ${r.status}`);render(box,data);}catch(e){console.warn('DraftIQ news:',e);renderError(box,e);}}
function refresh(){const p=panel();if(!p)return;const name=recommendedName(p);if(!name)return;const box=mount(p);if(name!==lastPlayer||!box.dataset.loaded){lastPlayer=name;box.dataset.loaded='1';load(name,box);}}
const obs=new MutationObserver(()=>requestAnimationFrame(refresh));window.addEventListener('load',()=>{refresh();const app=document.getElementById('app');if(app)obs.observe(app,{childList:true,subtree:true});});setInterval(refresh,5000);
})();