// FantasyPros news + expert note integration via Supabase Edge Function.
(function(){
const ENDPOINT='https://uinhyjqsqrgfczqrmcya.supabase.co/functions/v1/fantasypros-news';
let lastPlayer='';
const cache=new Map();
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function strip(v){const d=document.createElement('div');d.innerHTML=String(v??'');return (d.textContent||d.innerText||'').replace(/view fantasy impact\s*»?/ig,'').trim();}
function age(v){if(!v)return '';let s=String(v).trim();if(/^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}$/.test(s))s=s.replace(' ','T')+'Z';const d=new Date(s);if(Number.isNaN(d.getTime()))return '';const m=Math.max(0,Math.floor((Date.now()-d.getTime())/60000));if(m<60)return `${m}m ago`;const h=Math.floor(m/60);if(h<24)return `${h}h ago`;return `${Math.floor(h/24)}d ago`;}
function items(data){const candidates=[data?.items,data?.news,data?.results,data?.data?.items,data?.data,data?.players?.news];for(const x of candidates)if(Array.isArray(x))return x;return Array.isArray(data)?data:[];}
function normalize(n){const cats=Array.isArray(n?.categories)?n.categories.join(' • '):'';return {title:n?.title||n?.headline||n?.news_headline||n?.player_name||'Player Update',body:strip(n?.desc||n?.description||n?.analysis||n?.news||n?.summary||n?.body||n?.content||''),impact:strip(n?.impact||n?.fantasy_impact||''),date:n?.created||n?.updated||n?.published_at||n?.updated_at||n?.created_at||n?.date||n?.timestamp||'',type:cats||n?.type||n?.category||n?.news_type||'',link:n?.link||n?.url||''};}
function positionFor(name){try{return typeof player==='function'?(player(name)?.[1]||''):'';}catch{return '';}}
async function getData(name,pos=''){const key=`${name}|${pos}`;const hit=cache.get(key);if(hit&&Date.now()-hit.time<300000)return hit.data;const u=new URL(ENDPOINT);u.searchParams.set('player',name);if(pos)u.searchParams.set('position',pos);u.searchParams.set('limit','3');u.searchParams.set('_',Date.now());const r=await fetch(u.toString(),{cache:'no-store'});const data=await r.json();if(!r.ok)throw new Error(data?.error||`HTTP ${r.status}`);cache.set(key,{time:Date.now(),data});return data;}
function panel(){return document.querySelector('.cc-area-rec')||Array.from(document.querySelectorAll('.cockpit-panel')).find(p=>p.querySelector('.panel-title h3')?.textContent.includes('DraftIQ Recommendation'));}
function recommendedName(p){return p?.querySelector('.recommend-info h2')?.textContent?.trim()||'';}
function mount(p){let box=p.querySelector('.fp-news');if(!box){box=document.createElement('div');box.className='fp-news';const action=p.querySelector('.recommend-action');if(action)action.before(box);else p.appendChild(box);}return box;}
function renderLoading(box){box.innerHTML='<div class="fp-news-head"><b>LATEST NEWS + EXPERT NOTE</b><span>FantasyPros</span></div><div class="fp-news-loading">Checking FantasyPros…</div>';}
function expertHtml(data,compact=false){const e=data?.expert_note;if(!e?.text)return '';return `<div class="fp-expert${compact?' compact':''}"><div class="fp-expert-label">EXPERT NOTE</div><div class="fp-expert-text">${esc(e.text)}</div>${e.link?`<a href="${esc(e.link)}" target="_blank" rel="noopener">Full note on FantasyPros ↗</a>`:''}</div>`;}
function newsHtml(data,compact=false){const list=items(data).map(normalize).filter(x=>x.title||x.body||x.impact);if(!list.length)return `<div class="fp-news-empty">No recent FantasyPros news found for this player.</div>${expertHtml(data,compact)}`;const n=list[0];const source=n.link?`<a class="fp-news-source" href="${esc(n.link)}" target="_blank" rel="noopener">FantasyPros ↗</a>`:'FantasyPros';return `<div class="fp-news-title">${esc(n.title)}</div>${n.body?`<div class="fp-news-body${compact?' compact':''}">${esc(n.body)}</div>`:''}${n.impact?`<div class="fp-news-impact"><b>FANTASY IMPACT</b> ${esc(n.impact)}</div>`:''}<div class="fp-news-credit">${source}${n.date?` • ${esc(age(n.date))}`:''}</div>${expertHtml(data,compact)}`;}
function render(box,data){box.innerHTML=`<div class="fp-news-head"><b>LATEST NEWS + EXPERT NOTE</b><span>FantasyPros</span></div>${newsHtml(data,false)}`;}
function renderError(box,e){box.innerHTML=`<div class="fp-news-head"><b>LATEST NEWS + EXPERT NOTE</b><span>FantasyPros</span></div><div class="fp-news-empty">Player news temporarily unavailable.</div>`;console.warn('DraftIQ news:',e);}
async function load(name,box){renderLoading(box);try{render(box,await getData(name,positionFor(name)));}catch(e){renderError(box,e);}}
function refresh(){const p=panel();if(!p)return;const name=recommendedName(p);if(!name)return;const box=mount(p);if(name!==lastPlayer||!box.dataset.loaded){lastPlayer=name;box.dataset.loaded='1';load(name,box);}}
function ensurePopover(){let pop=document.querySelector('.fp-player-popover');if(pop)return pop;pop=document.createElement('div');pop.className='fp-player-popover';pop.innerHTML='<button class="fp-pop-close" aria-label="Close">×</button><div class="fp-pop-content"></div>';document.body.appendChild(pop);pop.querySelector('.fp-pop-close').addEventListener('click',()=>pop.classList.remove('open'));return pop;}
function placePopover(pop,anchor){const r=anchor?.getBoundingClientRect?.();if(!r){pop.style.left='50%';pop.style.top='90px';return;}const w=340,margin=10;let left=Math.min(window.innerWidth-w-margin,Math.max(margin,r.left-w+anchor.offsetWidth));let top=Math.min(window.innerHeight-260,Math.max(margin,r.bottom+6));pop.style.left=`${left}px`;pop.style.top=`${top}px`;}
async function showPlayerNews(name,pos,anchor){const pop=ensurePopover();const content=pop.querySelector('.fp-pop-content');content.innerHTML=`<div class="fp-pop-head"><b>${esc(name)}</b><span>FantasyPros</span></div><div class="fp-news-loading">Loading player update…</div>`;placePopover(pop,anchor);pop.classList.add('open');try{const data=await getData(name,pos||positionFor(name));content.innerHTML=`<div class="fp-pop-head"><b>${esc(name)}</b><span>FantasyPros</span></div>${newsHtml(data,true)}`;}catch(e){content.innerHTML=`<div class="fp-pop-head"><b>${esc(name)}</b><span>FantasyPros</span></div><div class="fp-news-empty">Player update unavailable.</div>`;}}
window.DraftIQShowPlayerNews=showPlayerNews;
document.addEventListener('click',e=>{const pop=document.querySelector('.fp-player-popover');if(!pop?.classList.contains('open'))return;if(pop.contains(e.target)||e.target.closest?.('.cc-news-btn'))return;pop.classList.remove('open');});
document.addEventListener('keydown',e=>{if(e.key==='Escape')document.querySelector('.fp-player-popover')?.classList.remove('open');});
const obs=new MutationObserver(()=>requestAnimationFrame(refresh));window.addEventListener('load',()=>{refresh();const app=document.getElementById('app');if(app)obs.observe(app,{childList:true,subtree:true});});setInterval(refresh,5000);
})();