(function(){
const FANTASY_NAMES={Sean:'JIMBO SLICE',Chris:"chris's First-Rate Team",Brian:"Ethan’s Dogshit Team",Hunter:'JUDKINS OUT ON BOND',Andy:'Insert in my Tight end',Cody:"Najee see me najee don't",Dave:'STOP.. Caleb-a-rate and Listen',Brandon:'Kickers are people too',Scott:'Rice Rice Baby',Phillip:"Philip's Pleasant Team"};
const TEAM_NAMES={ARI:'Arizona Cardinals',ATL:'Atlanta Falcons',BAL:'Baltimore Ravens',BUF:'Buffalo Bills',CAR:'Carolina Panthers',CHI:'Chicago Bears',CIN:'Cincinnati Bengals',CLE:'Cleveland Browns',DAL:'Dallas Cowboys',DEN:'Denver Broncos',DET:'Detroit Lions',GB:'Green Bay Packers',HOU:'Houston Texans',IND:'Indianapolis Colts',JAX:'Jacksonville Jaguars',KC:'Kansas City Chiefs',LAC:'Los Angeles Chargers',LAR:'Los Angeles Rams',LV:'Las Vegas Raiders',MIA:'Miami Dolphins',MIN:'Minnesota Vikings',NE:'New England Patriots',NO:'New Orleans Saints',NYG:'New York Giants',NYJ:'New York Jets',PHI:'Philadelphia Eagles',PIT:'Pittsburgh Steelers',SEA:'Seattle Seahawks',SF:'San Francisco 49ers',TB:'Tampa Bay Buccaneers',TEN:'Tennessee Titans',WAS:'Washington Commanders'};
const BYE={KC:5,CAR:5,CIN:6,DET:6,MIA:6,MIN:6,BUF:7,JAX:7,LAC:7,WAS:7,NYG:8,HOU:8,NO:8,SF:8,PIT:9,TEN:9,CHI:10,DEN:10,PHI:10,TB:10,SEA:11,LAR:11,ATL:11,NE:11,CLE:11,GB:11,BAL:13,NYJ:13,IND:13,LV:13,DAL:14,ARI:14};
let metaCache={};
function counts(team){const c={QB:0,RB:0,WR:0,TE:0};teamRoster(team).forEach(x=>{if(c[x.pos]!==undefined)c[x.pos]++;});return c;}
function needScores(team){const c=counts(team);const roundNow=Math.max(1,round(s.pick));const scores={
 QB:c.QB===0?100:c.QB===1?72:c.QB===2?24:5,
 RB:c.RB===0?100:c.RB===1?92:c.RB===2?68:c.RB===3?42:c.RB===4?20:8,
 WR:c.WR===0?100:c.WR===1?96:c.WR===2?88:c.WR===3?62:c.WR===4?38:c.WR===5?18:7,
 TE:c.TE===0?58:c.TE===1?18:c.TE===2?5:2
 };
 if(roundNow<=3){scores.RB+=c.RB<2?8:0;scores.WR+=c.WR<3?8:0;scores.QB+=c.QB<2?5:0;}
 return scores;
}
function teamNeeds(team){const scores=needScores(team);return Object.entries(scores).sort((a,b)=>b[1]-a[1]).map(([pos,score])=>({pos,score}));}
window.DraftIQTeamNeeds=teamNeeds;
function needBadges(team,limit=2){return teamNeeds(team).slice(0,limit).map((n,i)=>`<span class="need-badge ${i===0?'primary ':''}pos-${n.pos}">${n.pos}${i===0?' • PRIORITY':''}</span>`).join('');}
function initials(n){return String(n||'?').split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase();}
function meta(name){return metaCache[keyName(name)]||{team:'',player_id:''};}
function avatar(name){const m=meta(name);return m.player_id?`<img class="mt-avatar" src="https://sleepercdn.com/content/nfl/players/thumb/${m.player_id}.jpg" alt="" onerror="this.outerHTML='<span class=&quot;mt-avatar mt-fallback&quot;>${initials(name)}</span>'">`:`<span class="mt-avatar mt-fallback">${initials(name)}</span>`;}
function teamText(name){const m=meta(name),t=m.team||'TBD';return `${TEAM_NAMES[t]||t} • Bye ${BYE[t]||'—'}`;}
function myPicks(){const arr=[];for(let p=s.pick;p<=120;p++)if(owner(p)==='Scott')arr.push(p);return arr;}
rosterView=function(){
 const roster=myRoster(),c=counts('Scott'),needs=teamNeeds('Scott'),picks=myPicks(),proj=roster.reduce((sum,x)=>sum+(player(x.name)?.[3]||0),0),drafted=roster.filter(x=>!x.keeper).length,keepers=roster.filter(x=>x.keeper).length;
 const rows=roster.map(x=>{const p=player(x.name),m=meta(x.name);return `<div class="mt-player"><div class="mt-pos pos-${x.pos}">${x.pos||'—'}</div>${avatar(x.name)}<div class="mt-main"><b>${E(x.name)}</b><small>${E(teamText(x.name))}</small></div><div class="mt-metric"><b>${p?p[3].toFixed(1):'—'}</b><small>Proj Pts</small></div><div class="mt-metric"><b>${m.team||'TBD'}</b><small>NFL Team</small></div><div class="mt-tag ${x.keeper?'keeper':'drafted'}">${x.keeper?'KEEPER':x.pick?`PICK ${fmtPick(x.pick)}`:'DRAFTED'}</div></div>`}).join('');
 return `<div class="mt-page"><div class="mt-hero"><div><div class="mt-kicker">RED ZONE FRANCHISE HQ</div><h2>Rice Rice Baby</h2><p>Manager: Scott • Live roster, positional balance and upcoming draft priorities.</p></div><div class="mt-status"><strong>${roster.length} / 16</strong><span>ACTIVE ROSTER</span></div></div><div class="mt-summary"><div class="mt-summary-card"><span>Quarterbacks</span><strong class="pos-QB">${c.QB}</strong></div><div class="mt-summary-card"><span>Running Backs</span><strong class="pos-RB">${c.RB}</strong></div><div class="mt-summary-card"><span>Wide Receivers</span><strong class="pos-WR">${c.WR}</strong></div><div class="mt-summary-card"><span>Tight Ends</span><strong class="pos-TE">${c.TE}</strong></div><div class="mt-summary-card"><span>Projected Points</span><strong>${proj.toFixed(1)}</strong></div><div class="mt-summary-card"><span>Roster Openings</span><strong>${Math.max(0,16-roster.length)}</strong></div></div><div class="mt-layout"><section class="mt-panel"><div class="mt-panel-head"><h3>Official Team Roster</h3><div class="needs-inline"><span class="m">${keepers} keepers • ${drafted} drafted</span></div></div><div class="mt-roster">${rows||'<div class="lr-empty">No players rostered.</div>'}</div></section><aside class="mt-panel mt-needs-panel"><h3>Draft Priorities</h3><div class="mt-needs-big">${needs.map((n,i)=>`<div class="mt-need-row"><span class="pos-${n.pos}"><b>${n.pos}</b></span><div class="bar"><i style="width:${Math.min(100,n.score)}%"></i></div><strong>${i===0?'HIGH':i===1?'MED':'LOW'}</strong></div>`).join('')}</div><div class="mt-note">Needs are recalculated from the live roster and your league format: 1 QB, 2 RB, 3 WR, 2 W/R/T flex spots and a Q/W/R/T superflex. The model also adds depth pressure as the draft progresses.</div><div class="mt-picks"><h4>Upcoming Picks Owned</h4><div class="mt-pick-chips">${picks.slice(0,12).map(p=>`<span class="mt-pick-chip">${fmtPick(p)}</span>`).join('')||'<span class="m">No picks remaining.</span>'}</div></div></aside></div></div>`;
};
function decorateLeagueRosterNeeds(){document.querySelectorAll('.lr-team-card').forEach(card=>{const txt=card.textContent||'';const team=TEAMS.find(t=>txt.includes(`Manager: ${t}`));if(!team||card.querySelector('.lr-needs'))return;const meta=card.querySelector('.lr-team-meta');if(meta)meta.insertAdjacentHTML('afterend',`<div class="lr-needs"><span class="lr-needs-label">Draft Needs</span>${needBadges(team,3)}</div>`);});}
function decorateCommandNeeds(){const table=document.querySelector('.board-compact');if(!table||table.dataset.needs==='1')return;table.dataset.needs='1';const head=table.querySelector('tr');if(head)head.insertAdjacentHTML('beforeend','<th>Need</th>');Array.from(table.querySelectorAll('tr')).slice(1).forEach(tr=>{const text=tr.textContent||'';const team=TEAMS.find(t=>text.includes(t));if(team)tr.insertAdjacentHTML('beforeend',`<td class="need-cell">${needBadges(team,1)}</td>`);});const title=table.closest('.cockpit-panel')?.querySelector('.panel-title h3');if(title&&!title.querySelector('.cc-needs-note'))title.insertAdjacentHTML('beforeend','<span class="cc-needs-note">• live roster need</span>');}
const baseView=view;
view=function(v){baseView(v);if(v==='teams')setTimeout(decorateLeagueRosterNeeds,0);if(v==='command')setTimeout(decorateCommandNeeds,0);};
async function loadMeta(){try{const r=await fetch('https://api.sleeper.app/v1/players/nfl',{cache:'force-cache'});if(!r.ok)return;const data=await r.json();for(const id in data){const x=data[id];if(x?.full_name)metaCache[keyName(x.full_name)]={team:x.team||'',player_id:x.player_id||id};}if(document.querySelector('.mt-page'))view('roster');}catch(e){}}
loadMeta();
if(document.querySelector('.lr-page'))decorateLeagueRosterNeeds();if(document.querySelector('.cc-shell'))decorateCommandNeeds();
})();